### ISSUE TITLE
List of features for v1 release

### ISSUE THREAD

**Issue by bergos** [bergos/voice-engine-js#5]
- [X] [Recorder](https://github.com/bergos/voice-engine-js/blob/master/lib/Recorder.js) for audio input from a microphone.
- [X] [Keyword Spotting](https://github.com/bergos/voice-engine-js/blob/master/lib/AutoKeywordSpotting.js) including detection for the end of speech input.
  - [X] [Snowboy](https://github.com/bergos/voice-engine-js/blob/master/lib/SnowboyKeywordSpotting.js) is an [open source](https://github.com/Kitt-AI/snowboy) deep neural network based Keyword Spotting engine.
- [ ] [Direction of Arrival](https://github.com/bergos/voice-engine-js/issues/1) to detect the direction of speech input for Beamforming.
- [ ] [Beamforming](https://github.com/bergos/voice-engine-js/issues/2) for better audio quality based on the data from Direction of Arrival.
- [X] [Slice](https://github.com/bergos/voice-engine-js/blob/master/lib/Slice.js) to extract the audio after a keyword till the end of speech input.
- [X] [Speech to Text](https://github.com/bergos/voice-engine-js/blob/master/lib/AutoSpeechToText.js) to translate the speech input to text strings (including confidence and alternatives).
  - [X] [Google Speech API](https://github.com/bergos/voice-engine-js/blob/master/lib/GoogleSpeechToText.js) sends data to the cloud and is free up to 60min per month.
  - [X] [Wit.ai Speech API](https://github.com/bergos/voice-engine-js/blob/master/lib/WitSpeechToText.js) sends data to the cloud, is unlimited free but doesn't provide confidence and alternatives.
  - [ ] [offline](https://github.com/bergos/voice-engine-js/issues/3) is required for privacy aware applications.
- [ ] [Text to Speech](https://github.com/bergos/voice-engine-js/issues/4) one or more implementations should be provided for text output via audio.
  - [ ] offline is required for privacy aware applications.
- [X] LED interface for visual feedback for events like keyword detected, listening, etc.
  - [X] [ReSpeaker 4-Mic Array PixelRing](https://github.com/bergos/voice-engine-js/blob/master/lib/ReSpeaker4MicPixelRing.js) for the AP102 SPI based RGB LEDs on the [ReSpeaker 4-Mic Array](https://www.seeedstudio.com/ReSpeaker-4-Mic-Array-for-Raspberry-Pi-p-2941.html)
